fix: Add http:// to default influx module config (#869)
### Motivation
The current default influxdb module config throws an InfluxException
because the protocol is missing.

> Exception firing module task entry
eu.cloudnetservice.driver.module.DefaultModuleTaskEntry@665522c2
> com.influxdb.exceptions.InfluxException: Unable to parse connection
string 127.0.0.1:8086

### Modification
Added http:// to the default host

### Result
> Module eu.cloudnetservice.cloudnet:CloudNet-Influx:4.0.0-RC1 was
started successfully